### ISSUE TITLE
 ReferenceError: Unknown plugin "transform-vue-jsx" specified 

### ISSUE THREAD

**Issue by standfv** [grinmax/vue-smart-pagination#1]
ReferenceError: Unknown plugin "transform-vue-jsx" specified

**Comment by grinmax** [comment]
We don't use this plugin, what do you mean?

**Comment by standfv** [comment]
`Module build failed: ReferenceError: Unknown plugin "transform-vue-jsx" specified in "C:\\Users\\ktvn8\\Desktop\\livepubg\\client\\node_modules\\vue-smart-pagination\\.babelrc" at 0, attempted to resolve relative to "C:\\Users\\ktvn8\\Desktop\\livepubg\\client\\node_modules\\vue-smart-pagination"
    at C:\Users\ktvn8\Desktop\livepubg\client\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (C:\Users\ktvn8\Desktop\livepubg\client\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\Users\ktvn8\Desktop\livepubg\client\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\Users\ktvn8\Desktop\livepubg\client\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\Users\ktvn8\Desktop\livepubg\client\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Users\ktvn8\Desktop\livepubg\client\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Users\ktvn8\Desktop\livepubg\client\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Users\ktvn8\Desktop\livepubg\client\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (C:\Users\ktvn8\Desktop\livepubg\client\node_modules\babel-loader\lib\index.js:173:20)

 @ ./~/vue-smart-pagination/src/components/PaginationControl.vue 8:0-107 9:0-120
 @ ./~/vue-smart-pagination/src/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js`

**Comment by matiullah-karimi** [comment]
Same issue

**Comment by dimasi** [comment]
+1
